apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/install.yaml
  - argocd-ingress.yaml

patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm

# Patch to run server in insecure mode (HTTP)
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/args/0
      - op: add
        path: /spec/template/spec/containers/0/args/0
        value: --insecure
