apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 78.2.1
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - thanos-s3-secret.yaml
  - grafana-dashboard-stable-nav.yaml
  - grafana-dashboard-ops-main-navigation.yaml
  - grafana-dashboard-ops-nav-infrastructure.yaml
  - grafana-dashboard-ops-nav-kubernetes.yaml
  - grafana-dashboard-ops-nav-monitoring.yaml
  - grafana-dashboard-ops-nav-dataplatform.yaml
  - grafana-dashboard-multi-cluster-overview.yaml
