# NGINX Ingress Base Configuration
# NOTE: This is the base configuration. Cluster-specific hostnames are in overlays.

controller:
  replicaCount: 1

  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    proxy-body-size: "50m"

  admissionWebhooks:
    enabled: false
