# ============================================================================
# Cluster-02 Edge - Prometheus Agent Mode
# ============================================================================
# 엣지 클러스터 구성: Agent 모드로 중앙 클러스터에 Remote Write
# ============================================================================

# ============================================================================
# Prometheus 설정 (Agent Mode)
# ============================================================================
prometheus:
  enabled: true

  prometheusSpec:
    # --------------------------------------------------------------------
    # Agent Mode 활성화
    # --------------------------------------------------------------------
    additionalArgs:
      - name: enable-feature
        value: agent

    # --------------------------------------------------------------------
    # 클러스터 식별 레이블
    # --------------------------------------------------------------------
    externalLabels:
      cluster: cluster-04-edge
      environment: edge
      region: kr-edge-04

    # --------------------------------------------------------------------
    # Replica 설정 (경량 구성)
    # --------------------------------------------------------------------
    replicas: 1

    # --------------------------------------------------------------------
    # Remote Write 설정 (Thanos Receiver)
    # --------------------------------------------------------------------
    # 주의: writeRelabelConfigs에서 메트릭을 필터링하면 해당 메트릭만 전송됨
    # 모든 메트릭을 전송하려면 writeRelabelConfigs를 제거하거나 주석 처리
    remoteWrite:
      - url: http://thanos-receiver.k8s-cluster-01.miribit.lab/api/v1/receive

        # Remote Write Headers (옵션)
        # Thanos Receiver에서 클러스터 식별용
        # headers:
        #   THANOS-TENANT: cluster-04-edge

        # Queue 설정 최적화
        queueConfig:
          capacity: 10000
          maxShards: 10
          minShards: 1
          maxSamplesPerSend: 5000
          batchSendDeadline: 5s
          minBackoff: 30ms
          maxBackoff: 100ms

        # Write Relabel 설정 (선택 사항)
        # 특정 메트릭만 전송하거나 레이블 수정 시 사용
        # 현재는 주석 처리하여 모든 메트릭 전송
        #
        # writeRelabelConfigs:
        #   # 예시 1: 특정 메트릭만 전송 (비권장 - 대부분의 메트릭 누락)
        #   - sourceLabels: [__name__]
        #     regex: 'up|scrape_.*'
        #     action: keep
        #
        #   # 예시 2: 불필요한 메트릭 제외 (권장)
        #   - sourceLabels: [__name__]
        #     regex: 'go_.*|process_.*'
        #     action: drop
        #
        #   # 예시 3: 특정 레이블 제거 (카디널리티 감소)
        #   - regex: 'instance|pod'
        #     action: labeldrop

    # --------------------------------------------------------------------
    # 리소스 설정 (Agent는 경량)
    # --------------------------------------------------------------------
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

    # --------------------------------------------------------------------
    # 스토리지 설정 (Agent는 작은 WAL만 필요)
    # --------------------------------------------------------------------
    retention: 6h
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

    # --------------------------------------------------------------------
    # Thanos Sidecar 비활성화 (Agent 모드에서는 불필요)
    # --------------------------------------------------------------------
    thanos:
      enabled: false

# ============================================================================
# Alertmanager 비활성화 (중앙 클러스터에서만 필요)
# ============================================================================
alertmanager:
  enabled: false

# ============================================================================
# Grafana 비활성화 (중앙 클러스터에서만 필요)
# ============================================================================
grafana:
  enabled: false

# ============================================================================
# Kube State Metrics
# ============================================================================
kube-state-metrics:
  enabled: true

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# ============================================================================
# Node Exporter
# ============================================================================
prometheus-node-exporter:
  enabled: true

  hostNetwork: true
  hostPID: true

  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

# ============================================================================
# 기본 타겟 모니터링 활성화
# ============================================================================
kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: true

coreDns:
  enabled: true

kubeEtcd:
  enabled: false  # 엣지 클러스터에서는 불필요

kubeScheduler:
  enabled: true

kubeProxy:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
