apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-values-198
  namespace: logging
data:
  values.yaml: |
    # Cluster 198 Edge - OpenSearch Configuration

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: opensearch.mkube-198.miribit.lab
          paths:
            - path: /
              pathType: Prefix
