apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: fluent-operator
    repo: https://fluent.github.io/helm-charts
    version: 3.3.0
    releaseName: fluent-operator
    namespace: fluent-operator-system
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespace.yaml
