apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

# Thanos Sidecar는 kube-prometheus-stack에 내장되어 있음
# 중앙 클러스터(196)에서만 Query/Store/Compactor/Ruler 배포
# 엣지 클러스터(197, 198)는 Sidecar만 활성화

resources:
  - s3-secret.yaml
  # 아래 컴포넌트들은 overlay/cluster-196-central에서만 활성화됨
  # - thanos-query.yaml
  # - thanos-store.yaml
  # - thanos-compactor.yaml
  # - thanos-ruler.yaml
