apiVersion: v1
kind: Secret
metadata:
  name: thanos-s3-config
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: thanos
      endpoint: 172.20.40.21:30001
      access_key: minio
      secret_key: minio123
      insecure: true
