apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values-197
  namespace: monitoring
data:
  values.yaml: |
    # Cluster 197 Edge - Prometheus with Thanos Sidecar Only

    prometheus:
      prometheusSpec:
        # External labels for multi-cluster
        externalLabels:
          cluster: cluster-197-edge
          region: miribit-lab

        # Thanos Sidecar - 엣지 클러스터는 메트릭을 S3에 업로드만 함
        thanos:
          image: quay.io/thanos/thanos:v0.37.2
          version: v0.37.2
          objectStorageConfig:
            name: thanos-s3-config
            key: objstore.yml

    # Grafana - 로컬 접근만 (중앙 클러스터에서 통합 조회)
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.mkube-197.miribit.lab
        tls: []

    # Alertmanager - 로컬 접근만
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.mkube-197.miribit.lab
        tls: []
