# kube-prometheus-stack Base Configuration
# NOTE: This is the base configuration. Cluster-specific Thanos settings are in overlays.

# Global settings
global:
  evaluation_interval: 30s

# Prometheus Operator
prometheusOperator:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Prometheus instance
prometheus:
  enabled: true

  prometheusSpec:
    replicas: 1

    retention: 2h  # Constitution Principle III: max 2 hours local retention
    retentionSize: 10GB

    scrapeInterval: 30s  # From clarification
    evaluationInterval: 30s

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi

    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

    # Thanos sidecar configuration
    # NOTE: This is enabled in edge clusters (197, 198) via overlays
    # Central cluster (196) uses standalone Thanos components
    thanos:
      # Enabled per cluster in overlays
      # image: quay.io/thanos/thanos:v0.37.2
      # objectStorageConfig:
      #   name: thanos-s3-config
      #   key: objstore.yml

    # Service monitors
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

# Alertmanager
alertmanager:
  enabled: true

  alertmanagerSpec:
    replicas: 1

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

# Grafana
grafana:
  enabled: true

  replicas: 1

  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

  # Grafana ingress configured in overlays
  ingress:
    enabled: false

# Node Exporter
nodeExporter:
  enabled: true

# Kube State Metrics
kubeStateMetrics:
  enabled: true

# Default Service Monitors
defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false  # Not applicable to Minikube
    general: true
    k8s: true
    kubeApiserver: true
    kubeApiserverAvailability: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    network: true
    node: true
    prometheus: true
    prometheusOperator: true
