# ============================================================================
# Cluster-02 Edge - Prometheus Agent Mode
# ============================================================================
# 엣지 클러스터 구성: Agent 모드로 중앙 클러스터에 Remote Write
# ============================================================================

# ============================================================================
# Prometheus 설정 (Agent Mode)
# ============================================================================
prometheus:
  enabled: true

  prometheusSpec:
    # --------------------------------------------------------------------
    # Agent Mode 활성화
    # --------------------------------------------------------------------
    additionalArgs:
      - name: enable-feature
        value: agent

    # --------------------------------------------------------------------
    # 클러스터 식별 레이블
    # --------------------------------------------------------------------
    externalLabels:
      cluster: cluster-03-edge
      environment: edge
      region: kr-edge-03

    # --------------------------------------------------------------------
    # Replica 설정 (경량 구성)
    # --------------------------------------------------------------------
    replicas: 1

    # --------------------------------------------------------------------
    # Remote Write 설정 (Thanos Receiver)
    # --------------------------------------------------------------------
    remoteWrite:
      - url: http://thanos-receiver.k8s-cluster-01.miribit.lab/api/v1/receive
        queueConfig:
          capacity: 10000
          maxShards: 10
          minShards: 1
          maxSamplesPerSend: 5000
          batchSendDeadline: 5s
          minBackoff: 30ms
          maxBackoff: 100ms
        writeRelabelConfigs:
          - sourceLabels: [__name__]
            regex: 'up|scrape_.*'
            action: keep

    # --------------------------------------------------------------------
    # 리소스 설정 (Agent는 경량)
    # --------------------------------------------------------------------
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

    # --------------------------------------------------------------------
    # 스토리지 설정 (Agent는 작은 WAL만 필요)
    # --------------------------------------------------------------------
    retention: 6h
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

    # --------------------------------------------------------------------
    # Thanos Sidecar 비활성화 (Agent 모드에서는 불필요)
    # --------------------------------------------------------------------
    thanos:
      enabled: false

# ============================================================================
# Alertmanager 비활성화 (중앙 클러스터에서만 필요)
# ============================================================================
alertmanager:
  enabled: false

# ============================================================================
# Grafana 비활성화 (중앙 클러스터에서만 필요)
# ============================================================================
grafana:
  enabled: false

# ============================================================================
# Kube State Metrics
# ============================================================================
kube-state-metrics:
  enabled: true

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# ============================================================================
# Node Exporter
# ============================================================================
prometheus-node-exporter:
  enabled: true

  hostNetwork: true
  hostPID: true

  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
