apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-ingress-cluster-01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: http://gitea.k8s-cluster-01.miribit.lab/gitea_admin/thanos-multi-cluster.git
    targetRevision: main
    path: deploy/overlays/cluster-01-central/cilium-ingress
    plugin:
      name: kustomize-enable-helm

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
