---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-cluster-dashboards
  namespace: logging
spec:
  type: ClusterIP
  selector:
    opensearch.cluster.dashboards: opensearch-cluster
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
