---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: logging
spec:
  general:
    serviceName: opensearch-cluster
    version: 2.11.0
    httpPort: 9200
    vendor: opensearch

  dashboards:
    enable: true
    version: 2.11.0
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m

  confMgmt:
    smartScaler: true

  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30Gi
      roles:
        - cluster_manager
        - data
      persistence:
        emptyDir: {}
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 4Gi
          cpu: 1000m
      jvm: -Xmx1g -Xms1g

    - component: data
      replicas: 3
      diskSize: 100Gi
      roles:
        - data
        - ingest
      persistence:
        emptyDir: {}
      resources:
        requests:
          memory: 4Gi
          cpu: 1000m
        limits:
          memory: 8Gi
          cpu: 2000m
      jvm: -Xmx2g -Xms2g

  security:
    config:
      adminCredentialsSecret:
        name: opensearch-admin-credentials
      securityConfigSecret:
        name: opensearch-security-config
    tls:
      transport:
        generate: true
      http:
        generate: true
