apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: opensearch-operator
    repo: https://opensearch-project.github.io/opensearch-k8s-operator
    version: 2.6.0
    releaseName: opensearch-operator
    namespace: opensearch-operator-system
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespace.yaml
