---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: logging
spec:
  general:
    pluginsList:
      - repository-s3

  bootstrap:
    additionalConfig:
      s3.client.default.endpoint: s3.minio.miribit.lab:9000
      s3.client.default.protocol: http

  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30Gi
      roles:
        - cluster_manager
        - data
      persistence:
        storageClass: longhorn
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 4Gi
          cpu: 1000m

    - component: data
      replicas: 3
      diskSize: 100Gi
      roles:
        - data
        - ingest
      persistence:
        storageClass: longhorn
      resources:
        requests:
          memory: 4Gi
          cpu: 1000m
        limits:
          memory: 8Gi
          cpu: 2000m
