---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-s3-credentials
  namespace: logging
type: Opaque
stringData:
  s3.client.default.access_key: ${S3_ACCESS_KEY}
  s3.client.default.secret_key: ${S3_SECRET_KEY}
