apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-values-197
  namespace: logging
data:
  values.yaml: |
    # Cluster 197 Edge - Fluent Bit Configuration

    config:
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Kube_URL https://kubernetes.default.svc:443
            Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix kube.var.log.containers.
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
            Labels On
            Annotations Off

        [FILTER]
            Name nest
            Match kube.*
            Operation lift
            Nested_under kubernetes
            Add_prefix k8s_

        [FILTER]
            Name modify
            Match kube.*
            Add cluster cluster-197-edge

        [FILTER]
            Name modify
            Match host.*
            Add cluster cluster-197-edge

      outputs: |
        [OUTPUT]
            Name opensearch
            Match kube.*
            Host opensearch-cluster-master.logging.svc.cluster.local
            Port 9200
            Index logs
            Type _doc
            Logstash_Format On
            Logstash_Prefix logs-k8s
            Logstash_DateFormat %Y.%m.%d
            Time_Key @timestamp
            Generate_ID On
            Replace_Dots On
            Retry_Limit 5
            Suppress_Type_Name On
            tls Off

        [OUTPUT]
            Name opensearch
            Match host.*
            Host opensearch-cluster-master.logging.svc.cluster.local
            Port 9200
            Index logs
            Type _doc
            Logstash_Format On
            Logstash_Prefix logs-host
            Logstash_DateFormat %Y.%m.%d
            Time_Key @timestamp
            Generate_ID On
            Replace_Dots On
            Retry_Limit 5
            Suppress_Type_Name On
            tls Off
