apiVersion: v1
kind: Secret
metadata:
  name: thanos-s3-config
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: "thanos-cluster-01"
      endpoint: "s3.minio.miribit.lab:80"
      access_key: "Kl8u9VGxT4KA8TxlLEfO"
      secret_key: "U9KVRsMZlHJtiToriOxXfl9uPAXqFjqAI1ZdRCOz"
      insecure: true
      http_config:
        insecure_skip_verify: false
