---
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-external
  namespace: monitoring
  labels:
    app: prometheus
    thanos-sidecar: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.101.213
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prometheus-stack-prometheus
