# ============================================================================
# Base Kustomization - kube-prometheus-stack
# ============================================================================
# Helm을 통해 kube-prometheus-stack 차트를 렌더링
# ============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace 생성
namespace: monitoring

# Helm 차트 설정
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: "78.5.0"
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true
