apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

helmCharts:
  - name: fluent-bit
    repo: https://fluent.github.io/helm-charts
    version: 0.49.2
    releaseName: fluent-bit
    namespace: logging
    valuesFile: values.yaml

resources: []
