---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-storage
  namespace: gitlab
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    aws_access_key_id: ${S3_ACCESS_KEY}
    aws_secret_access_key: ${S3_SECRET_KEY}
    host: s3.minio.miribit.lab
    endpoint: http://s3.minio.miribit.lab:9000
    path_style: true
