---
# Thanos Sidecar를 외부에서 접근 가능하도록 NodePort 서비스 생성
# 중앙 클러스터의 Thanos Query가 이 엔드포인트로 접근
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar-external
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
      nodePort: 30901
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack-prometheus
