---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit-cluster-02
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability

  source:
    repoURL: http://gitea.k8s-cluster-01.miribit.lab/gitea_admin/thanos-multi-cluster.git
    targetRevision: main
    path: deploy/overlays/cluster-02-edge/fluentbit

  destination:
    server: https://192.168.101.196:6443
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
