---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-04-edge
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster-04-edge
  server: https://192.168.101.198:6443
  config: |
    {
      "tlsClientConfig": {
        "insecure": false,
        "caData": "${CLUSTER_04_CA_DATA}",
        "certData": "${CLUSTER_04_CERT_DATA}",
        "keyData": "${CLUSTER_04_KEY_DATA}"
      }
    }
